### ISSUE TITLE
Is sync required in `applicationDidEnterBackground` and `applicationWillTerminate`?

### ISSUE THREAD

**Issue by rdougan** [brandnetworks/BNEasyGoogleAnalytics#1]
Thanks for the great library. Much nicer to use the Google's.

Simple question: is sync required in `applicationDidEnterBackground` and `applicationWillTerminate` in your AppDelegate?

**Comment by bmnick** [comment]
Yes, manual sync is required on for `applicationDidEnterBackground` and `applicationWillTerminate`. `applicationWillTerminate` I believe will actually clear the queue, so that's absolutely required, but `applicationDidEnterBackground` should keep them cached locally until you come back into focus. It really depends on how time sensitive the analytics are as compared to network access and power. 

I'd love to work on making this automatic in the future but it's probably going to be a bit before I can dedicate the time to getting it there.

**Comment by rdougan** [comment]
OK great, thanks!
